apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "online-store.fullname" . }}-counter
  labels:
    app: {{ template "online-store.name" . }}-counter
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.counter.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "online-store.name" . }}-counter
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "online-store.name" . }}-counter
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "online-store.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.counter.image.repository }}:{{ .Values.counter.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: {{ .Values.counter.image.pullPolicy }}
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: LABEL_SELECTOR
              value: "app={{ template "online-store.name" . }}"
            - name: SCRAPE_INTERVAL
              value: {{ .Values.counter.interval | quote }}
            - name: SPECIAL_NODE_NAME
              value: {{ required "A value is required for counter.specialNodeName" .Values.counter.specialNodeName}}
